USE [master]
GO

/****** Object:  Database [Motobike]    Script Date: 07/01/2024 8:58:01 PM ******/
CREATE DATABASE [Motobike]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Motobike', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\Motobike.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Motobike_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\Motobike_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Motobike].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Motobike] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Motobike] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Motobike] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Motobike] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Motobike] SET ARITHABORT OFF 
GO

ALTER DATABASE [Motobike] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Motobike] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Motobike] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Motobike] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Motobike] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Motobike] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Motobike] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Motobike] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Motobike] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Motobike] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Motobike] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Motobike] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Motobike] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Motobike] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Motobike] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Motobike] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Motobike] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Motobike] SET RECOVERY FULL 
GO

ALTER DATABASE [Motobike] SET  MULTI_USER 
GO

ALTER DATABASE [Motobike] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Motobike] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Motobike] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Motobike] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Motobike] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Motobike] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Motobike] SET QUERY_STORE = ON
GO

ALTER DATABASE [Motobike] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [Motobike] SET  READ_WRITE 
GO


USE [Motobike]
GO

/****** Object:  Table [dbo].[Customer]    Script Date: 07/01/2024 8:58:25 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Customer](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](150) NULL,
	[PhoneNumber] [nvarchar](50) NULL,
	[Count] [int] NULL,
 CONSTRAINT [PK_Customer] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

USE [Motobike]
GO

/****** Object:  Table [dbo].[Motobike]    Script Date: 07/01/2024 8:58:40 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Motobike](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](150) NULL,
	[YearModel] [int] NULL,
	[TypeId] [int] NULL,
	[TypeName] [nvarchar](150) NULL,
	[Price] [money] NULL,
 CONSTRAINT [PK_Motobike] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Motobike]  WITH CHECK ADD  CONSTRAINT [FK_Motobike_MotoType] FOREIGN KEY([TypeId])
REFERENCES [dbo].[MotoType] ([Id])
GO

ALTER TABLE [dbo].[Motobike] CHECK CONSTRAINT [FK_Motobike_MotoType]
GO

USE [Motobike]
GO

/****** Object:  Table [dbo].[MotoType]    Script Date: 07/01/2024 8:58:57 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[MotoType](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](150) NULL,
 CONSTRAINT [PK_MotoType] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

USE [Motobike]
GO

/****** Object:  Table [dbo].[Rent]    Script Date: 07/01/2024 8:59:10 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Rent](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[CustomerId] [int] NULL,
	[Name] [nvarchar](150) NULL,
	[PhoneNumber] [nvarchar](50) NULL,
	[CCCD] [nvarchar](50) NULL,
	[Address] [nvarchar](500) NULL,
	[MotoID] [int] NULL,
	[MotoName] [nvarchar](50) NULL,
	[Days] [int] NULL,
	[Total] [money] NULL,
	[StartDate] [date] NULL,
	[EndDate] [date] NULL,
 CONSTRAINT [PK_Rent] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Rent]  WITH CHECK ADD  CONSTRAINT [FK_Rent_Customer] FOREIGN KEY([CustomerId])
REFERENCES [dbo].[Customer] ([Id])
GO

ALTER TABLE [dbo].[Rent] CHECK CONSTRAINT [FK_Rent_Customer]
GO

ALTER TABLE [dbo].[Rent]  WITH CHECK ADD  CONSTRAINT [FK_Rent_Motobike] FOREIGN KEY([MotoID])
REFERENCES [dbo].[Motobike] ([Id])
GO

ALTER TABLE [dbo].[Rent] CHECK CONSTRAINT [FK_Rent_Motobike]
GO

USE [Motobike]
GO

/****** Object:  Table [dbo].[UserLogin]    Script Date: 07/01/2024 8:59:22 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[UserLogin](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Username] [nvarchar](10) NULL,
	[Password] [nvarchar](10) NULL,
	[Role] [int] NULL,
 CONSTRAINT [PK_UserLogin] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

